// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdqdlvyrqzokgalmzmof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkcWRsdnlycXpva2dhbG16bW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzMyNzUsImV4cCI6MjA2NzU0OTI3NX0.YcwSWy0rSH8NZJpNK0fZ0WY57vXSnsXELThKwu1NScE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});